In [1]:
import pandas as pd
import numpy as np
dataset=pd.read_csv('D:\\ml\Corona_NLP_test.csv')
print(dataset.head())

                                       OriginalTweet Sentiment
0  TRENDING: New Yorkers encounter empty supermar...  Negative
1  When I couldn't find hand sanitizer at Fred Me...  Positive
2  Find out how you can protect yourself and love...  Positive
3  #Panic buying hits #NewYork City as anxious sh...  Negative
4  #toiletpaper #dunnypaper #coronavirus #coronav...   Neutral


In [36]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
clean = []
for i in range(0, 3798):
  tweet = re.sub('[^a-zA-Z]', ' ', dataset['OriginalTweet'][i])
  tweet = tweet.lower()
  tweet = tweet.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  tweet = [ps.stem(word) for word in tweet if not word in set(all_stopwords)]
  tweet = ' '.join(tweet)
  clean.append(tweet)
print(clean)

[nltk_data] Downloading package stopwords to C:\Users\Swapnil
[nltk_data]     Jaiswal\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['trend new yorker encount empti supermarket shelv pictur wegman brooklyn sold onlin grocer foodkick maxdeliveri coronaviru fear shopper stock http co gr pcrlwh http co ivmkmsqdt', 'find hand sanit fred meyer turn amazon pack purel check coronaviru concern drive price http co ygbipbflmi', 'find protect love one coronaviru', 'panic buy hit newyork citi anxiou shopper stock food amp medic suppli healthcar worker becom bigappl st confirm coronaviru patient bloomberg stage event http co iasiregpc qanon qanon qanon elect cdc http co iszoewxu', 'toiletpap dunnypap coronaviru coronavirusaustralia coronavirusupd covid news corvid newsmelb dunnypaperg costco one week everyon buy babi milk powder next everyon buy toilet paper http co sczryvvsih', 'rememb last time paid gallon regular ga lo angel price pump go look coronaviru impact price pm abc http co pyzq ymuv', 'vote age coronaviru hand sanit supertuesday http co z bel dk', 'drtedro stop covid without protect healthwork price surgic mask incr

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 10000)
X = cv.fit_transform(clean).toarray()
y = dataset.iloc[:, -1].values

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10, random_state = 2)

In [44]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [45]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Negative' 'Negative']
 ['Negative' 'Negative']
 ['Negative' 'Negative']
 ['Negative' 'Negative']
 ['Negative' 'Negative']
 ['Neutral' 'Neutral']
 ['Negative' 'Negative']
 ['Neutral' 'Positive']
 ['Neutral' 'Positive']
 ['Negative' 'Negative']
 ['Neutral' 'Neutral']
 ['Negative' 'Negative']
 ['Positive' 'Positive']
 ['Negative' 'Neutral']
 ['Positive' 'Negative']
 ['Negative' 'Negative']
 ['Negative' 'Negative']
 ['Neutral' 'Neutral']
 ['Positive' 'Positive']
 ['Negative' 'Neutral']
 ['Negative' 'Positive']
 ['Neutral' 'Neutral']
 ['Neutral' 'Positive']
 ['Negative' 'Neutral']
 ['Positive' 'Positive']
 ['Positive' 'Positive']
 ['Negative' 'Negative']
 ['Negative' 'Positive']
 ['Neutral' 'Neutral']
 ['Negative' 'Positive']
 ['Positive' 'Neutral']
 ['Neutral' 'Positive']
 ['Negative' 'Positive']
 ['Positive' 'Positive']
 ['Positive' 'Neutral']
 ['Positive' 'Positive']
 ['Negative' 'Negative']
 ['Negative' 'Negative']
 ['Positive' 'Negative']
 ['Negative' 'Negative']
 ['Negative' 'Neutr

In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
E=accuracy_score(y_test, y_pred)*100
print('Efficiency =',E,'%')

[[103  13  47]
 [ 22  40  14]
 [ 51  17  73]]
Efficiency = 56.84210526315789 %
